#!/usr/bin/env python3
"""Reproject an LROC south-polar stereographic DTM into LunCoSim's local DEM frame.

The current ``lunco-assets`` DEM cropper intentionally refuses polar-stereographic
products because its native crop affine is equirectangular-only. NOBILE03 is a
small, official LROC PDS product, so this tool is the explicit boundary adapter:

* it validates the PDS3 label and the source GeoTIFF's float32/uncompressed layout;
* it maps a local ENU square (X=east, -Z=north) to the source polar projection;
* it writes a square, node-based, float32 GeoTIFF with the same georeferencing
  contract as ``lunco-assets``;
* it never downloads anything and it never modifies the raw source.

Only the standard library is used so the adapter can run before optional GIS
tools are installed. The source and generated bytes belong in ignored cache/
terrain paths; the manifest, command parameters, and provenance belong in Git.
"""

from __future__ import annotations

import argparse
import math
import re
import struct
from pathlib import Path


MOON_RADIUS_M = 1_737_400.0
NODATA_F32 = -3.40282266e38


class TiffError(ValueError):
    pass


def align(value: int, boundary: int = 8) -> int:
    return (value + boundary - 1) // boundary * boundary


def type_size(tiff_type: int) -> int:
    sizes = {1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8, 11: 4, 12: 8}
    try:
        return sizes[tiff_type]
    except KeyError as exc:
        raise TiffError(f"unsupported TIFF field type {tiff_type}") from exc


def read_tiff_field(blob: bytes, tiff_type: int, count: int, value_bytes: bytes) -> list[object]:
    total = type_size(tiff_type) * count
    raw = (value_bytes[:total] if total <= 4 else blob[struct.unpack_from("<I", value_bytes)[0] :][:total])
    if len(raw) != total:
        raise TiffError("TIFF field points outside the file")
    formats = {
        1: f"<{count}B",
        2: f"<{count}s",
        3: f"<{count}H",
        4: f"<{count}I",
        5: None,
        7: f"<{count}B",
        8: f"<{count}h",
        9: f"<{count}i",
        11: f"<{count}f",
        12: f"<{count}d",
    }
    if tiff_type == 2:
        return [raw.rstrip(b"\0").decode("ascii", errors="strict")]
    if tiff_type == 5:
        return [n / d for n, d in struct.iter_unpack("<II", raw) if d]
    fmt = formats.get(tiff_type)
    if fmt is None:
        raise TiffError(f"unsupported TIFF field type {tiff_type}")
    return list(struct.unpack(fmt, raw))


def read_source_tiff(path: Path) -> tuple[int, int, list[float], dict[int, list[object]]]:
    blob = path.read_bytes()
    if blob[:2] != b"II" or struct.unpack_from("<H", blob, 2)[0] != 42:
        raise TiffError(f"{path} is not a little-endian classic TIFF")
    ifd_offset = struct.unpack_from("<I", blob, 4)[0]
    count = struct.unpack_from("<H", blob, ifd_offset)[0]
    fields: dict[int, list[object]] = {}
    entries_offset = ifd_offset + 2
    for index in range(count):
        tag, tiff_type, item_count = struct.unpack_from("<HHI", blob, entries_offset + index * 12)
        value_bytes = blob[entries_offset + index * 12 + 8 : entries_offset + index * 12 + 12]
        fields[tag] = read_tiff_field(blob, tiff_type, item_count, value_bytes)

    def one(tag: int, name: str) -> object:
        try:
            values = fields[tag]
            return values[0]
        except (KeyError, IndexError) as exc:
            raise TiffError(f"source TIFF is missing {name} (tag {tag})") from exc

    width = int(one(256, "ImageWidth"))
    height = int(one(257, "ImageLength"))
    bits = int(one(258, "BitsPerSample"))
    compression = int(one(259, "Compression"))
    samples = int(one(277, "SamplesPerPixel"))
    sample_format = int(one(339, "SampleFormat"))
    if bits != 32 or compression != 1 or samples != 1 or sample_format != 3:
        raise TiffError(
            "source must be one-channel, uncompressed, little-endian float32 "
            f"(bits={bits}, compression={compression}, samples={samples}, sample_format={sample_format})"
        )

    offsets = [int(value) for value in fields.get(273, [])]
    byte_counts = [int(value) for value in fields.get(279, [])]
    if len(offsets) != len(byte_counts):
        raise TiffError("source StripOffsets and StripByteCounts have different lengths")
    rows_per_strip = int(one(278, "RowsPerStrip"))
    samples_out = [math.nan] * (width * height)
    for strip_offset, byte_count, strip_index in zip(offsets, byte_counts, range(len(offsets))):
        raw = blob[strip_offset : strip_offset + byte_count]
        rows = min(rows_per_strip, height - strip_index * rows_per_strip)
        expected = rows * width * 4
        if len(raw) != expected:
            raise TiffError(f"source strip {strip_index} has {len(raw)} bytes, expected {expected}")
        values = struct.unpack(f"<{rows * width}f", raw)
        start = strip_index * rows_per_strip * width
        samples_out[start : start + len(values)] = values
    if any(math.isfinite(value) and abs(value) < 1e-30 for value in samples_out):
        # A zero is a valid lunar elevation, so this is only a diagnostic hook;
        # no value is rejected here. The explicit nodata sentinel is handled by
        # finite checks while resampling below.
        pass
    return width, height, samples_out, fields


def read_label(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="ascii", errors="strict")
    if not re.search(r'MAP_PROJECTION_TYPE\s*=\s*"POLARSTEREOGRAPHIC"', text):
        raise TiffError(f"{path} is not labelled MAP_PROJECTION_TYPE = \"POLARSTEREOGRAPHIC\"")
    values: dict[str, str] = {}
    for key in (
        "MAP_SCALE",
        "CENTER_LATITUDE",
        "CENTER_LONGITUDE",
        "MINIMUM_LATITUDE",
        "MAXIMUM_LATITUDE",
        "WESTERNMOST_LONGITUDE",
        "EASTERNMOST_LONGITUDE",
    ):
        match = re.search(rf"^\s*{key}\s*=\s*([^\r\n]+)", text, flags=re.MULTILINE)
        if match:
            values[key] = match.group(1).strip()
    return values


def float_value(fields: dict[int, list[object]], tag: int, name: str, count: int) -> list[float]:
    values = fields.get(tag)
    if values is None or len(values) < count:
        raise TiffError(f"source TIFF is missing {name} (tag {tag})")
    return [float(value) for value in values[:count]]


def polar_to_lat_lon(x: float, y: float, radius_m: float) -> tuple[float, float]:
    rho = math.hypot(x, y)
    lat = -math.pi / 2.0 + 2.0 * math.atan(rho / (2.0 * radius_m))
    lon = math.atan2(x, y)
    return math.degrees(lat), math.degrees(lon) % 360.0


def destination(lat0_deg: float, lon0_deg: float, east_m: float, north_m: float, radius_m: float) -> tuple[float, float]:
    distance = math.hypot(east_m, north_m)
    if distance == 0.0:
        return lat0_deg, lon0_deg
    bearing = math.atan2(east_m, north_m)
    lat0 = math.radians(lat0_deg)
    lon0 = math.radians(lon0_deg)
    angular = distance / radius_m
    lat = math.asin(
        math.sin(lat0) * math.cos(angular)
        + math.cos(lat0) * math.sin(angular) * math.cos(bearing)
    )
    lon = lon0 + math.atan2(
        math.sin(bearing) * math.sin(angular) * math.cos(lat0),
        math.cos(angular) - math.sin(lat0) * math.sin(lat),
    )
    return math.degrees(lat), math.degrees(lon) % 360.0


def bilinear(samples: list[float], width: int, height: int, px: float, py: float) -> float:
    if not (0.0 <= px <= width - 1 and 0.0 <= py <= height - 1):
        raise TiffError(f"requested local window falls outside source at pixel ({px:.3f}, {py:.3f})")
    x0 = min(width - 1, max(0, math.floor(px)))
    y0 = min(height - 1, max(0, math.floor(py)))
    x1 = min(width - 1, x0 + 1)
    y1 = min(height - 1, y0 + 1)
    tx = px - x0
    ty = py - y0
    corners = (
        samples[y0 * width + x0],
        samples[y0 * width + x1],
        samples[y1 * width + x0],
        samples[y1 * width + x1],
    )
    weights = ((1.0 - tx) * (1.0 - ty), tx * (1.0 - ty), (1.0 - tx) * ty, tx * ty)
    valid = [
        (value, weight)
        for value, weight in zip(corners, weights)
        if math.isfinite(value) and value > -1.0e30
    ]
    total_weight = sum(weight for _, weight in valid)
    if total_weight > 1.0e-12:
        # NOBILE03 contains small internal voids. Renormalising the measured
        # bilinear corners is the same local interpolation contract as the
        # native DEM processor's void fill; it never invents a broad edge apron.
        return sum(value * weight for value, weight in valid) / total_weight
    # Exact sampling on a missing node gives all zero bilinear weights. Find a
    # nearby measured node only for that isolated case; a larger unsupported
    # hole remains a hard error instead of becoming a fabricated surface.
    nearest: list[tuple[float, float]] = []
    ix = round(px)
    iy = round(py)
    for radius in range(1, 5):
        for sy in range(max(0, iy - radius), min(height, iy + radius + 1)):
            for sx in range(max(0, ix - radius), min(width, ix + radius + 1)):
                value = samples[sy * width + sx]
                if math.isfinite(value) and value > -1.0e30:
                    distance = math.hypot(sx - px, sy - py)
                    nearest.append((distance, value))
        if nearest:
            distance, value = min(nearest)
            if distance <= 4.0:
                return value
            break
    raise TiffError(f"source nodata reached output sample at pixel ({px:.3f}, {py:.3f})")


def inline_short(value: int) -> bytes:
    return struct.pack("<H", value) + b"\0\0"


def inline_long(value: int) -> bytes:
    return struct.pack("<I", value)


def write_geotiff(path: Path, values: list[float], resolution: int, window_m: float, center_lat: float, center_lon: float, radius_m: float) -> None:
    scale = window_m / (resolution - 1)
    half = window_m / 2.0
    geo_doubles = [radius_m, radius_m, center_lat, center_lon]
    # 14 keys, with external values in the same ASCII/double arrays the
    # geotiff-core writer emits. Key ordering is by id and never positional.
    geo_keys = [
        1, 1, 0, 14,
        1024, 0, 1, 1,
        1025, 0, 1, 2,
        1026, 34737, 8, 0,
        2048, 0, 1, 32767,
        2049, 34737, 10, 8,
        2054, 0, 1, 9102,
        2057, 34736, 1, 0,
        2058, 34736, 1, 1,
        3072, 0, 1, 32767,
        3074, 0, 1, 32767,
        3075, 0, 1, 17,
        3076, 0, 1, 9001,
        3078, 34736, 1, 2,
        3088, 34736, 1, 3,
    ]
    ascii_params = b"MOON_ME|Moon 2000|"
    pixel_scale = struct.pack("<3d", scale, scale, 0.0)
    tiepoint = struct.pack("<6d", 0.0, 0.0, 0.0, -half, half, 0.0)
    doubles = struct.pack("<4d", *geo_doubles)
    keys = struct.pack(f"<{len(geo_keys)}H", *geo_keys)
    pixel_bytes = struct.pack(f"<{len(values)}f", *values)

    # Classic TIFF: one IFD and one strip, all little-endian. The only values
    # that do not fit inline are appended after the IFD and aligned to 8 bytes.
    entries = [
        (256, 3, 1, inline_short(resolution)),
        (257, 3, 1, inline_short(resolution)),
        (258, 3, 1, inline_short(32)),
        (259, 3, 1, inline_short(1)),
        (262, 3, 1, inline_short(1)),
        (273, 4, 1, None),
        (277, 3, 1, inline_short(1)),
        (278, 4, 1, inline_long(resolution)),
        (279, 4, 1, inline_long(len(pixel_bytes))),
        (284, 3, 1, inline_short(1)),
        (339, 3, 1, inline_short(3)),
        (33550, 12, 3, None),
        (33922, 12, 6, None),
        (34735, 3, len(geo_keys), None),
        (34736, 12, 4, None),
        (34737, 2, len(ascii_params), None),
    ]
    ifd_start = 8
    extra_start = align(ifd_start + 2 + len(entries) * 12 + 4)
    extra = bytearray()

    def add_extra(payload: bytes) -> int:
        nonlocal extra
        absolute = align(extra_start + len(extra))
        extra.extend(b"\0" * (absolute - (extra_start + len(extra))))
        extra.extend(payload)
        return absolute

    scale_offset = add_extra(pixel_scale)
    tiepoint_offset = add_extra(tiepoint)
    keys_offset = add_extra(keys)
    doubles_offset = add_extra(doubles)
    ascii_offset = add_extra(ascii_params)
    strip_offset = align(extra_start + len(extra))
    entries[5] = (273, 4, 1, inline_long(strip_offset))
    entries[11] = (33550, 12, 3, inline_long(scale_offset))
    entries[12] = (33922, 12, 6, inline_long(tiepoint_offset))
    entries[13] = (34735, 3, len(geo_keys), inline_long(keys_offset))
    entries[14] = (34736, 12, 4, inline_long(doubles_offset))
    entries[15] = (34737, 2, len(ascii_params), inline_long(ascii_offset))

    output = bytearray(b"II" + struct.pack("<H", 42) + struct.pack("<I", ifd_start))
    output.extend(struct.pack("<H", len(entries)))
    for tag, tiff_type, count, value_bytes in entries:
        if value_bytes is None or len(value_bytes) != 4:
            raise TiffError(f"internal writer error for TIFF tag {tag}")
        output.extend(struct.pack("<HHI", tag, tiff_type, count))
        output.extend(value_bytes)
    output.extend(struct.pack("<I", 0))
    output.extend(b"\0" * (extra_start - len(output)))
    output.extend(extra)
    output.extend(b"\0" * (strip_offset - len(output)))
    output.extend(pixel_bytes)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="raw LROC float32 GeoTIFF")
    parser.add_argument("--label", type=Path, required=True, help="matching LROC PDS3 label")
    parser.add_argument("--output", type=Path, required=True, help="generated heightmap.tif")
    parser.add_argument("--center-lat", type=float, required=True, help="local frame centre, degrees")
    parser.add_argument("--center-lon", type=float, required=True, help="local frame centre, 0-360 degrees east")
    parser.add_argument("--window-m", type=float, default=512.0)
    parser.add_argument("--resolution", type=int, default=129)
    parser.add_argument("--body-radius-m", type=float, default=MOON_RADIUS_M)
    parser.add_argument(
        "--vertical-offset",
        type=float,
        default=0.0,
        help="metres added to source heights for the local scene datum; pass -<border datum> explicitly",
    )
    args = parser.parse_args()
    if args.resolution < 2 or args.window_m <= 0.0 or args.body_radius_m <= 0.0:
        parser.error("window, body radius, and resolution must be positive; resolution must be >= 2")
    label = read_label(args.label)
    width, height, source, fields = read_source_tiff(args.source)
    scale = float_value(fields, 33550, "ModelPixelScale", 2)
    tie = float_value(fields, 33922, "ModelTiepoint", 6)
    if abs(scale[0] - scale[1]) > 1e-9 or scale[0] <= 0.0:
        raise TiffError(f"source pixel scale must be square and positive, got {scale[:2]}")
    if not math.isfinite(args.center_lon) or not 0.0 <= args.center_lon <= 360.0:
        raise TiffError("center longitude must use the LROC 0-360 degrees-east convention")
    # The source tiepoint/scale is authoritative for pixel placement. Report its
    # footprint so a changed upstream product cannot be mistaken for NOBILE03.
    corners = []
    for px, py in ((0, 0), (width - 1, 0), (0, height - 1), (width - 1, height - 1)):
        x = tie[3] + scale[0] * px
        y = tie[4] - scale[1] * py
        corners.append(polar_to_lat_lon(x, y, args.body_radius_m))
    print(f"source: {args.source} ({width}x{height}, {scale[0]:.3f} m/pixel)")
    print(f"label: projection=POLARSTEREOGRAPHIC, scale={label.get('MAP_SCALE', 'unknown')}")
    print("source footprint: " + ", ".join(f"lat={lat:.6f},lon={lon:.6f}" for lat, lon in corners))
    print(f"local frame: center=({args.center_lat:.8f},{args.center_lon:.8f}), window={args.window_m:g} m, res={args.resolution}")

    half = args.window_m / 2.0
    step = args.window_m / (args.resolution - 1)
    output: list[float] = []
    for row in range(args.resolution):
        north = half - row * step
        for col in range(args.resolution):
            east = -half + col * step
            lat, lon = destination(args.center_lat, args.center_lon, east, north, args.body_radius_m)
            # South-polar stereographic inverse: x is east of the pole and y is
            # north in the projection's convention, matching lon=atan2(x, y).
            rho = 2.0 * args.body_radius_m * math.tan((math.radians(lat) + math.pi / 2.0) / 2.0)
            angle = math.radians(lon)
            model_x = rho * math.sin(angle)
            model_y = rho * math.cos(angle)
            px = (model_x - tie[3]) / scale[0]
            py = (tie[4] - model_y) / scale[1]
            output.append(bilinear(source, width, height, px, py) + args.vertical_offset)

    finite = [value for value in output if math.isfinite(value)]
    border = [
        output[index]
        for index in range(len(output))
        if index < args.resolution
        or index >= len(output) - args.resolution
        or index % args.resolution == 0
        or index % args.resolution == args.resolution - 1
    ]
    border.sort()
    print(f"output stats: min={min(finite):.3f} max={max(finite):.3f} border_datum={border[len(border) // 2]:.3f} m")
    print(f"vertical offset: {args.vertical_offset:.3f} m")
    write_geotiff(args.output, output, args.resolution, args.window_m, args.center_lat, args.center_lon, args.body_radius_m)
    print(f"wrote: {args.output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except TiffError as error:
        raise SystemExit(f"reproject_lroc_polar_dem: error: {error}")
